version: '3.3'

services:
  db:
    build: 
      context: .
      dockerfile: scripts/Dockerfile.db
    environment:
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 1433:1433
    secrets:
      - db_password 

  server:
    image: selearning:latest 
    build:
      context: .
      dockerfile: scripts/Dockerfile.prod
    environment:
      ConnectionStrings__SELearning_FILE: /run/secrets/connection_string
      ConnectionStrings__ProductionConnectionString_FILE: /run/secrets/connection_string
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/cert.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password_FILE: /run/secrets/cert_password
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - db
    secrets:
      - connection_string
      - cert_password
    volumes:
      - './.local:/https/'

secrets:
  db_password:
    file: './.local/db_password.txt'
  connection_string:
    file: './.local/connection_string.txt'
  cert_password:
    file: './.local/cert_password.txt'