name: Build and Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ secrets.REGISTRY_SERVER }}/selearning-image:${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup git repo
        uses: actions/checkout@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build docker image
        run: docker build . -t ${{ env.IMAGE_TAG }}
      
      - name: Push docker image
        run: docker push ${{ env.IMAGE_TAG }}

      - name: Deploy image to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SELearningApp'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.IMAGE_TAG }}
