name: Build and Deploy

on:
  pull_request:
    branches:
      - master
  release:
    types: [published]

env:
  AZURE_WEBAPP_NAME: SELearning
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup git repo
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true
      - name: Install wasm tools
        run: dotnet workload install wasm-tools
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        working-directory: ./SELearning.API
        run: dotnet build --configuration Release
      - name: Publish
        working-directory: ./SELearning.API
        run: dotnet publish -c Release -o ../'${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/selearning'
      - name: Deploy to azure
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/selearning' 

