name: Check formatting

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Setup git repo
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - name: Install wasm tools
        run: dotnet workload install wasm-tools
      - name: Check formatting
        run: dotnet format --verbosity detailed --verify-no-changes
