name: Infrastructure

on:
  workflow_dispatch:
  release:
    types: [published]
    paths:
      - .github/workflows/infrastructure.yml
      - .infrastructure/**

env:
  RESOURCE_GROUP_NAME: SELearningRG
  LOCATION: northeurope
  SQL_SERVER_NAME: selearning
  DATABASE_NAME: SELearning
  WEBAPP_NAME: SELearningApp

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: infrastructure
          path: .infrastructure/


  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build
    environment: Production

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: infrastructure
          path: .infrastructure/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.LOCATION }}
      
      - name: Validate Azure Resource Deployment
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          region: ${{ env.LOCATION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: .infrastructure/main.bicep
          deploymentMode: Validate
          parameters: .infrastructure/azure.parameters.json


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - test
    environment: Production

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: infrastructure
          path: .infrastructure/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy Azure Resources
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          region: ${{ env.LOCATION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: .infrastructure/main.bicep
          deploymentMode: Incremental
          parameters: .infrastructure/azure.parameters.json
